# Website
title: Florent du4
owner: Florent Dufour
email: florent@dufour.xyz
description: >-
  Welcome to my landing page!
url: "https://dufour.xyz"
title_separator: " | "
language: en
encoding: utf-8
timezone: Europe/Paris
keywords: "florent, dufour, landing, welcome, presentation, cv, xyz, blockchain, biotechnology, health, AI, Munich, München"
theme-color: "#fdf52b"
theme-color-dark: "#333"

kramdown:
  parse_block_html: true

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
